import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './main_component/navbar/page'
import Second_section from './main_component/second_section/page'
import Third_section from "./main_component/third_section/page";
import Fourth_section from "./main_component/fourth_section/page";
import Fifth_section from "./main_component/fifth_section/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <br/>
        <Second_section />
        <Third_section />
        <Fourth_section />
        <Fifth_section />
        </body>
    </html>
  );
}
